#file: noinspection undefined
spring:
  task:
    scheduling:
      pool:
        size: 5
  graphql:
    graphiql:
      enabled: true
    path: /graphql

  data:
    mongodb:
      database: football
      uri: "mongodb+srv://sistemas:u7ubSAQugdF5Sd4y@yohersa-cluster0.zubfzw7.mongodb.net"

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

